name: CI Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  schedule:
    - cron: "0 0 * * *"  

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Python environment
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run static code analysis
        run: |
          flake8 ./

      - name: Run unit tests
        run: |
          pytest tests/

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/Lump1/DataAnalysis_college_datasets_python:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CICDPIPELINE_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/Lump1/DataAnalysis_college_datasets_python:latest

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "✅ Build completed successfully!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
